package com.example.dagger2.activits;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;

import android.os.Bundle;
import android.util.Log;

import com.example.dagger2.daggerclass.Coffee;
import com.example.dagger2.DaggerCoffeeComponent;
import com.example.dagger2.R;
import com.example.dagger2.component.CoffeeComponent;
import com.example.dagger2.databinding.ActivityMainBinding;

import javax.inject.Inject;

public class MainActivity extends AppCompatActivity {

    public ActivityMainBinding binding;
    private static final String TAG = "MainActivity";

    @Inject
    Coffee coffee;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main);

        // Generated by dagger.
        CoffeeComponent component = DaggerCoffeeComponent.create();

        // work on inject function in activity.
        component.inject(this);

        Log.d(TAG, "onCreate: "+ coffee.getCoffeeCup());
    }
}