package com.example.dagger2.activits;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;

import android.os.Bundle;
import android.util.Log;

import com.example.dagger2.component.AppComponent;
import com.example.dagger2.component.DaggerCoffeeComponent;
import com.example.dagger2.daggerclass.Coffee;
import com.example.dagger2.R;
import com.example.dagger2.component.CoffeeComponent;
import com.example.dagger2.databinding.ActivityMainBinding;
import com.example.dagger2.mainapplication.MainApplication;

import javax.inject.Inject;

public class MainActivity extends AppCompatActivity {

    public ActivityMainBinding binding;
    private static final String TAG = "MainActivity";

    @Inject
    Coffee coffee , coffee2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_main);

        // Generated by dagger. operation work dagger2 before add constructor in module.
        // CoffeeComponent component = DaggerCoffeeComponent.create();

        // Generated by dagger. operation work dagger2 after add constructor in module.
        //CoffeeComponent component = DaggerCoffeeComponent.builder().coffeeModule(new CoffeeModule(3)).build();

        // this Generate after add @component.builder
        //CoffeeComponent component = DaggerCoffeeComponent.builder().sugar(4).milk(7).build();

        //  this Generate after create main application because we need one instance from dagger in all application site.
        AppComponent component = ((MainApplication)getApplication()).getAppComponent();

        CoffeeComponent coffeeComponent = DaggerCoffeeComponent.builder().milk(4).sugar(7).appComponent(component).build();

        // work on inject function in activity.
        coffeeComponent.inject(this);
                                                                        // get coffee instance number.
        Log.d(TAG, "mohamed onCreate: "+ "\nCoffee1"+ coffee +"\nCoffee2: "+ coffee2 +"\n river to Coffee1 no :"+coffee.river + "river to Coffee2 no :"+ coffee2.river);
    }
}